# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IntroWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IntroWidget(object):
    def setupUi(self, IntroWidget):
        IntroWidget.setObjectName("IntroWidget")
        IntroWidget.resize(676, 542)
        IntroWidget.setMinimumSize(QtCore.QSize(676, 542))
        self.verticalLayout = QtWidgets.QVBoxLayout(IntroWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.WelcomeLabel = QtWidgets.QLabel(IntroWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.WelcomeLabel.setFont(font)
        self.WelcomeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.WelcomeLabel.setScaledContents(False)
        self.WelcomeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.WelcomeLabel.setWordWrap(True)
        self.WelcomeLabel.setObjectName("WelcomeLabel")
        self.verticalLayout.addWidget(self.WelcomeLabel)
        self.InstructionsLabel = QtWidgets.QLabel(IntroWidget)
        self.InstructionsLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.InstructionsLabel.setFont(font)
        self.InstructionsLabel.setMouseTracking(True)
        self.InstructionsLabel.setAcceptDrops(False)
        self.InstructionsLabel.setAutoFillBackground(False)
        self.InstructionsLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.InstructionsLabel.setTextFormat(QtCore.Qt.RichText)
        self.InstructionsLabel.setScaledContents(False)
        self.InstructionsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.InstructionsLabel.setWordWrap(True)
        self.InstructionsLabel.setIndent(-1)
        self.InstructionsLabel.setObjectName("InstructionsLabel")
        self.verticalLayout.addWidget(self.InstructionsLabel)
        self.LabelHelpLabel = QtWidgets.QLabel(IntroWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LabelHelpLabel.setFont(font)
        self.LabelHelpLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LabelHelpLabel.setTextFormat(QtCore.Qt.RichText)
        self.LabelHelpLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.LabelHelpLabel.setWordWrap(True)
        self.LabelHelpLabel.setObjectName("LabelHelpLabel")
        self.verticalLayout.addWidget(self.LabelHelpLabel)
        self.TaskOverviewLabel = QtWidgets.QLabel(IntroWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TaskOverviewLabel.setFont(font)
        self.TaskOverviewLabel.setTextFormat(QtCore.Qt.AutoText)
        self.TaskOverviewLabel.setWordWrap(True)
        self.TaskOverviewLabel.setObjectName("TaskOverviewLabel")
        self.verticalLayout.addWidget(self.TaskOverviewLabel)
        self.TaskListHeaderLabel = QtWidgets.QLabel(IntroWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TaskListHeaderLabel.setFont(font)
        self.TaskListHeaderLabel.setTextFormat(QtCore.Qt.AutoText)
        self.TaskListHeaderLabel.setWordWrap(True)
        self.TaskListHeaderLabel.setObjectName("TaskListHeaderLabel")
        self.verticalLayout.addWidget(self.TaskListHeaderLabel)
        self.TaskListVertLayout = QtWidgets.QVBoxLayout()
        self.TaskListVertLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.TaskListVertLayout.setContentsMargins(30, -1, -1, -1)
        self.TaskListVertLayout.setSpacing(6)
        self.TaskListVertLayout.setObjectName("TaskListVertLayout")
        self.TaskListLabel_1 = QtWidgets.QLabel(IntroWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskListLabel_1.sizePolicy().hasHeightForWidth())
        self.TaskListLabel_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TaskListLabel_1.setFont(font)
        self.TaskListLabel_1.setMouseTracking(True)
        self.TaskListLabel_1.setAcceptDrops(False)
        self.TaskListLabel_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TaskListLabel_1.setTextFormat(QtCore.Qt.AutoText)
        self.TaskListLabel_1.setScaledContents(False)
        self.TaskListLabel_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TaskListLabel_1.setWordWrap(True)
        self.TaskListLabel_1.setIndent(-1)
        self.TaskListLabel_1.setObjectName("TaskListLabel_1")
        self.TaskListVertLayout.addWidget(self.TaskListLabel_1)
        self.TaskListLabel_4 = QtWidgets.QLabel(IntroWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskListLabel_4.sizePolicy().hasHeightForWidth())
        self.TaskListLabel_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TaskListLabel_4.setFont(font)
        self.TaskListLabel_4.setMouseTracking(True)
        self.TaskListLabel_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TaskListLabel_4.setTextFormat(QtCore.Qt.AutoText)
        self.TaskListLabel_4.setScaledContents(False)
        self.TaskListLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TaskListLabel_4.setWordWrap(True)
        self.TaskListLabel_4.setIndent(-1)
        self.TaskListLabel_4.setObjectName("TaskListLabel_4")
        self.TaskListVertLayout.addWidget(self.TaskListLabel_4)
        self.TaskListLabel_2 = QtWidgets.QLabel(IntroWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskListLabel_2.sizePolicy().hasHeightForWidth())
        self.TaskListLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TaskListLabel_2.setFont(font)
        self.TaskListLabel_2.setMouseTracking(True)
        self.TaskListLabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TaskListLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.TaskListLabel_2.setScaledContents(False)
        self.TaskListLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TaskListLabel_2.setWordWrap(True)
        self.TaskListLabel_2.setIndent(-1)
        self.TaskListLabel_2.setObjectName("TaskListLabel_2")
        self.TaskListVertLayout.addWidget(self.TaskListLabel_2)
        self.TaskListLabel_3 = QtWidgets.QLabel(IntroWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskListLabel_3.sizePolicy().hasHeightForWidth())
        self.TaskListLabel_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TaskListLabel_3.setFont(font)
        self.TaskListLabel_3.setMouseTracking(True)
        self.TaskListLabel_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TaskListLabel_3.setTextFormat(QtCore.Qt.AutoText)
        self.TaskListLabel_3.setScaledContents(False)
        self.TaskListLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TaskListLabel_3.setWordWrap(True)
        self.TaskListLabel_3.setIndent(-1)
        self.TaskListLabel_3.setObjectName("TaskListLabel_3")
        self.TaskListVertLayout.addWidget(self.TaskListLabel_3)
        self.TaskListLabel_5 = QtWidgets.QLabel(IntroWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskListLabel_5.sizePolicy().hasHeightForWidth())
        self.TaskListLabel_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TaskListLabel_5.setFont(font)
        self.TaskListLabel_5.setMouseTracking(True)
        self.TaskListLabel_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TaskListLabel_5.setTextFormat(QtCore.Qt.AutoText)
        self.TaskListLabel_5.setScaledContents(False)
        self.TaskListLabel_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TaskListLabel_5.setWordWrap(True)
        self.TaskListLabel_5.setIndent(-1)
        self.TaskListLabel_5.setObjectName("TaskListLabel_5")
        self.TaskListVertLayout.addWidget(self.TaskListLabel_5)
        self.verticalLayout.addLayout(self.TaskListVertLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 69, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.BottomHoriLayout = QtWidgets.QHBoxLayout()
        self.BottomHoriLayout.setObjectName("BottomHoriLayout")
        self.AcceptCheckBox = QtWidgets.QCheckBox(IntroWidget)
        self.AcceptCheckBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AcceptCheckBox.sizePolicy().hasHeightForWidth())
        self.AcceptCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(False)
        font.setUnderline(False)
        self.AcceptCheckBox.setFont(font)
        self.AcceptCheckBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.AcceptCheckBox.setAcceptDrops(False)
        self.AcceptCheckBox.setAutoFillBackground(True)
        self.AcceptCheckBox.setIconSize(QtCore.QSize(15, 15))
        self.AcceptCheckBox.setCheckable(True)
        self.AcceptCheckBox.setChecked(False)
        self.AcceptCheckBox.setTristate(False)
        self.AcceptCheckBox.setObjectName("AcceptCheckBox")
        self.BottomHoriLayout.addWidget(self.AcceptCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.BottomHoriLayout.addItem(spacerItem1)
        self.ContinueButton = QtWidgets.QPushButton(IntroWidget)
        self.ContinueButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ContinueButton.setFont(font)
        self.ContinueButton.setCheckable(False)
        self.ContinueButton.setChecked(False)
        self.ContinueButton.setAutoRepeat(False)
        self.ContinueButton.setAutoExclusive(False)
        self.ContinueButton.setAutoDefault(False)
        self.ContinueButton.setDefault(False)
        self.ContinueButton.setFlat(False)
        self.ContinueButton.setObjectName("ContinueButton")
        self.BottomHoriLayout.addWidget(self.ContinueButton)
        self.verticalLayout.addLayout(self.BottomHoriLayout)
        self.ContactMeLabel = QtWidgets.QLabel(IntroWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContactMeLabel.sizePolicy().hasHeightForWidth())
        self.ContactMeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ContactMeLabel.setFont(font)
        self.ContactMeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ContactMeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.ContactMeLabel.setScaledContents(False)
        self.ContactMeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ContactMeLabel.setWordWrap(True)
        self.ContactMeLabel.setOpenExternalLinks(True)
        self.ContactMeLabel.setObjectName("ContactMeLabel")
        self.verticalLayout.addWidget(self.ContactMeLabel)

        self.retranslateUi(IntroWidget)
        self.AcceptCheckBox.clicked['bool'].connect(self.ContinueButton.toggle)
        self.ContinueButton.clicked.connect(IntroWidget.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(IntroWidget)

    def retranslateUi(self, IntroWidget):
        _translate = QtCore.QCoreApplication.translate
        IntroWidget.setWindowTitle(_translate("IntroWidget", "ALJI Label Helper Introduction"))
        self.WelcomeLabel.setText(_translate("IntroWidget", "Welcome"))
        self.InstructionsLabel.setText(_translate("IntroWidget", "<html><head/><body><p>Thank you for contributing to the <span style=\" font-weight:600;\">A</span>ctive <span style=\" font-weight:600;\">L</span>istening <span style=\" font-weight:600;\">J</span>ournal <span style=\" font-weight:600;\">I</span>nteraction (<span style=\" font-weight:600;\">ALJI</span>) project.  ALJI is a program designed to support the counseling of college students with depression by privately responding to their expressive writing or personal journal entries.     </p></body></html>"))
        self.LabelHelpLabel.setText(_translate("IntroWidget", "<html><head/><body><p>This program is used to label the dataset that will be used in the training and testing of ALJI.  The ALJI program can learn how to detect when an author is going through a mental health crisis based off of their expressive language and the labels you assign to certain language.  </p></body></html>"))
        self.TaskOverviewLabel.setText(_translate("IntroWidget", "You are given between 7-10 journal entries to read and label, which will take roughly 30 minutes to complete.  Follow the instructions at the end to send in your labels to be included in the ALJI project."))
        self.TaskListHeaderLabel.setText(_translate("IntroWidget", "It is important you follow this guide when labelling journal entries:"))
        self.TaskListLabel_1.setText(_translate("IntroWidget", "• Read the entire passage as if it is an entry in someone\'s personal journal or diary"))
        self.TaskListLabel_4.setText(_translate("IntroWidget", "• Consider the mental wellness of the author (assume the author is a high school senior in the USA, age 18)"))
        self.TaskListLabel_2.setText(_translate("IntroWidget", "• Highlight sentences that are either concerning (with yellow) or a major risk (with red)"))
        self.TaskListLabel_3.setText(_translate("IntroWidget", "• If you feel there is no need to approach the author with mental health support, then simply continue to the next journal entry.  Otherwise:"))
        self.TaskListLabel_5.setText(_translate("IntroWidget", "• Mark checkboxes according to what crisis labels apply to the sentences you selected.  You may add your own custom labels if needed."))
        self.AcceptCheckBox.setText(_translate("IntroWidget", "I Agree that I am qualified for this task"))
        self.ContinueButton.setText(_translate("IntroWidget", "Continue to Tasks"))
        self.ContactMeLabel.setText(_translate("IntroWidget", "<html><head/><body><p>Email Patrick Sullivan\n"
"(<a href=\"mailto:sublime@vt.edu?subject=ALJI Label Helper question\"><span style=\" text-decoration: underline; color:#0000ff;\">sublime@vt.edu</span></a>)\n"
"\n"
"for any questions you have on the project. \n"
"\n"
"</p></body></html>"))

