# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabelingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LabelingWidget(object):
    def setupUi(self, LabelingWidget):
        LabelingWidget.setObjectName("LabelingWidget")
        font = QtGui.QFont()
        font.setPointSize(13)
        LabelingWidget.setFont(font)
        self.hl_5 = QtWidgets.QHBoxLayout(LabelingWidget)
        self.hl_5.setObjectName("hl_5")
        self.journalEntryText = QtWidgets.QTextEdit(LabelingWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journalEntryText.sizePolicy().hasHeightForWidth())
        self.journalEntryText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.journalEntryText.setFont(font)
        self.journalEntryText.setMouseTracking(True)
        self.journalEntryText.setReadOnly(True)
        self.journalEntryText.setObjectName("journalEntryText")
        self.hl_5.addWidget(self.journalEntryText)
        self.labelingFrame = QtWidgets.QFrame(LabelingWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelingFrame.sizePolicy().hasHeightForWidth())
        self.labelingFrame.setSizePolicy(sizePolicy)
        self.labelingFrame.setObjectName("labelingFrame")
        self.labelingLayout = QtWidgets.QVBoxLayout(self.labelingFrame)
        self.labelingLayout.setObjectName("labelingLayout")
        self.navLayout = QtWidgets.QHBoxLayout()
        self.navLayout.setObjectName("navLayout")
        self.backButton = QtWidgets.QToolButton(self.labelingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/chevron-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon)
        self.backButton.setIconSize(QtCore.QSize(20, 20))
        self.backButton.setObjectName("backButton")
        self.navLayout.addWidget(self.backButton)
        self.taskNumberLabel = QtWidgets.QLabel(self.labelingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskNumberLabel.sizePolicy().hasHeightForWidth())
        self.taskNumberLabel.setSizePolicy(sizePolicy)
        self.taskNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.taskNumberLabel.setObjectName("taskNumberLabel")
        self.navLayout.addWidget(self.taskNumberLabel)
        self.forwardButton = QtWidgets.QToolButton(self.labelingFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/chevron-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon1)
        self.forwardButton.setIconSize(QtCore.QSize(20, 20))
        self.forwardButton.setObjectName("forwardButton")
        self.navLayout.addWidget(self.forwardButton)
        self.labelingLayout.addLayout(self.navLayout)
        self.crisisGroupBox = QtWidgets.QGroupBox(self.labelingFrame)
        self.crisisGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.crisisGroupBox.setObjectName("crisisGroupBox")
        self.crisisGroupBoxLayout = QtWidgets.QVBoxLayout(self.crisisGroupBox)
        self.crisisGroupBoxLayout.setObjectName("crisisGroupBoxLayout")
        self.crisisFrame = QtWidgets.QFrame(self.crisisGroupBox)
        self.crisisFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.crisisFrame.setObjectName("crisisFrame")
        self.hl3 = QtWidgets.QHBoxLayout(self.crisisFrame)
        self.hl3.setObjectName("hl3")
        self.crisisCB = QtWidgets.QCheckBox(self.crisisFrame)
        self.crisisCB.setObjectName("crisisCB")
        self.hl3.addWidget(self.crisisCB)
        self.deleteCrisis = QtWidgets.QToolButton(self.crisisFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/times.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteCrisis.setIcon(icon2)
        self.deleteCrisis.setIconSize(QtCore.QSize(20, 20))
        self.deleteCrisis.setObjectName("deleteCrisis")
        self.hl3.addWidget(self.deleteCrisis)
        self.crisisGroupBoxLayout.addWidget(self.crisisFrame)
        self.customCrisisFrame = QtWidgets.QFrame(self.crisisGroupBox)
        self.customCrisisFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.customCrisisFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.customCrisisFrame.setObjectName("customCrisisFrame")
        self._4 = QtWidgets.QHBoxLayout(self.customCrisisFrame)
        self._4.setObjectName("_4")
        self.customCrisisTextBox = QtWidgets.QPlainTextEdit(self.customCrisisFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customCrisisTextBox.sizePolicy().hasHeightForWidth())
        self.customCrisisTextBox.setSizePolicy(sizePolicy)
        self.customCrisisTextBox.setMinimumSize(QtCore.QSize(0, 35))
        self.customCrisisTextBox.setObjectName("customCrisisTextBox")
        self._4.addWidget(self.customCrisisTextBox)
        self.addCustomButton = QtWidgets.QToolButton(self.customCrisisFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addCustomButton.setIcon(icon3)
        self.addCustomButton.setIconSize(QtCore.QSize(20, 20))
        self.addCustomButton.setObjectName("addCustomButton")
        self._4.addWidget(self.addCustomButton)
        self.crisisGroupBoxLayout.addWidget(self.customCrisisFrame)
        self.labelingLayout.addWidget(self.crisisGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.labelingLayout.addItem(spacerItem)
        self.fontLayout = QtWidgets.QHBoxLayout()
        self.fontLayout.setObjectName("fontLayout")
        self.fontComboBox = QtWidgets.QFontComboBox(self.labelingFrame)
        self.fontComboBox.setFontFilters(QtWidgets.QFontComboBox.ProportionalFonts)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.fontLayout.addWidget(self.fontComboBox)
        self.pointSizeSpinBox = QtWidgets.QSpinBox(self.labelingFrame)
        self.pointSizeSpinBox.setMinimum(5)
        self.pointSizeSpinBox.setMaximum(30)
        self.pointSizeSpinBox.setProperty("value", 11)
        self.pointSizeSpinBox.setObjectName("pointSizeSpinBox")
        self.fontLayout.addWidget(self.pointSizeSpinBox)
        self.labelingLayout.addLayout(self.fontLayout)
        self.hl_5.addWidget(self.labelingFrame)

        self.retranslateUi(LabelingWidget)
        self.deleteCrisis.clicked.connect(self.crisisFrame.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(LabelingWidget)
        LabelingWidget.setTabOrder(self.journalEntryText, self.deleteCrisis)
        LabelingWidget.setTabOrder(self.deleteCrisis, self.customCrisisTextBox)
        LabelingWidget.setTabOrder(self.customCrisisTextBox, self.addCustomButton)
        LabelingWidget.setTabOrder(self.addCustomButton, self.backButton)
        LabelingWidget.setTabOrder(self.backButton, self.forwardButton)
        LabelingWidget.setTabOrder(self.forwardButton, self.fontComboBox)
        LabelingWidget.setTabOrder(self.fontComboBox, self.pointSizeSpinBox)

    def retranslateUi(self, LabelingWidget):
        _translate = QtCore.QCoreApplication.translate
        LabelingWidget.setWindowTitle(_translate("LabelingWidget", "ALJI Label Helper Task"))
        self.journalEntryText.setHtml(_translate("LabelingWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.journalEntryText.setPlaceholderText(_translate("LabelingWidget", "PLACEHOLDER TEXT"))
        self.backButton.setText(_translate("LabelingWidget", "Back"))
        self.backButton.setShortcut(_translate("LabelingWidget", "Ctrl+Left"))
        self.taskNumberLabel.setText(_translate("LabelingWidget", "Journal Entry ??/??"))
        self.forwardButton.setText(_translate("LabelingWidget", "Forward"))
        self.forwardButton.setShortcut(_translate("LabelingWidget", "Ctrl+Right"))
        self.crisisGroupBox.setTitle(_translate("LabelingWidget", "Crisis Labels"))
        self.crisisCB.setText(_translate("LabelingWidget", "Crisis1"))
        self.deleteCrisis.setText(_translate("LabelingWidget", "Delete"))
        self.customCrisisTextBox.setPlaceholderText(_translate("LabelingWidget", "add custom crisis label..."))
        self.addCustomButton.setText(_translate("LabelingWidget", "Add"))
        self.pointSizeSpinBox.setSuffix(_translate("LabelingWidget", " pt."))

