# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabelingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LabelingWidget(object):
    def setupUi(self, LabelingWidget):
        LabelingWidget.setObjectName("LabelingWidget")
        LabelingWidget.resize(1047, 715)
        LabelingWidget.setMinimumSize(QtCore.QSize(702, 373))
        font = QtGui.QFont()
        font.setPointSize(13)
        LabelingWidget.setFont(font)
        self.hl_5 = QtWidgets.QHBoxLayout(LabelingWidget)
        self.hl_5.setObjectName("hl_5")
        self.journalEntryText = QtWidgets.QTextEdit(LabelingWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journalEntryText.sizePolicy().hasHeightForWidth())
        self.journalEntryText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.journalEntryText.setFont(font)
        self.journalEntryText.setMouseTracking(True)
        self.journalEntryText.setReadOnly(True)
        self.journalEntryText.setObjectName("journalEntryText")
        self.hl_5.addWidget(self.journalEntryText)
        self.labelingFrame = QtWidgets.QFrame(LabelingWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelingFrame.sizePolicy().hasHeightForWidth())
        self.labelingFrame.setSizePolicy(sizePolicy)
        self.labelingFrame.setObjectName("labelingFrame")
        self.labelingLayout = QtWidgets.QVBoxLayout(self.labelingFrame)
        self.labelingLayout.setObjectName("labelingLayout")
        self.navFrame = QtWidgets.QFrame(self.labelingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navFrame.sizePolicy().hasHeightForWidth())
        self.navFrame.setSizePolicy(sizePolicy)
        self.navFrame.setObjectName("navFrame")
        self.navLayout = QtWidgets.QHBoxLayout(self.navFrame)
        self.navLayout.setSpacing(20)
        self.navLayout.setObjectName("navLayout")
        self.backButton = QtWidgets.QToolButton(self.navFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/chevron-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon)
        self.backButton.setIconSize(QtCore.QSize(20, 20))
        self.backButton.setObjectName("backButton")
        self.navLayout.addWidget(self.backButton)
        self.taskNumberLabel = QtWidgets.QLabel(self.navFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskNumberLabel.sizePolicy().hasHeightForWidth())
        self.taskNumberLabel.setSizePolicy(sizePolicy)
        self.taskNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.taskNumberLabel.setObjectName("taskNumberLabel")
        self.navLayout.addWidget(self.taskNumberLabel)
        self.forwardButton = QtWidgets.QToolButton(self.navFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forwardButton.sizePolicy().hasHeightForWidth())
        self.forwardButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/chevron-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon1)
        self.forwardButton.setIconSize(QtCore.QSize(20, 20))
        self.forwardButton.setObjectName("forwardButton")
        self.navLayout.addWidget(self.forwardButton)
        self.labelingLayout.addWidget(self.navFrame)
        self.cgiFrame = QtWidgets.QFrame(self.labelingFrame)
        self.cgiFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cgiFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cgiFrame.setObjectName("cgiFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.cgiFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cgiLabel = QtWidgets.QLabel(self.cgiFrame)
        self.cgiLabel.setObjectName("cgiLabel")
        self.horizontalLayout.addWidget(self.cgiLabel)
        self.cgiSspinBox = QtWidgets.QSpinBox(self.cgiFrame)
        self.cgiSspinBox.setMinimum(1)
        self.cgiSspinBox.setMaximum(7)
        self.cgiSspinBox.setObjectName("cgiSspinBox")
        self.horizontalLayout.addWidget(self.cgiSspinBox)
        self.labelingLayout.addWidget(self.cgiFrame)
        self.crisisGroupBox = QtWidgets.QGroupBox(self.labelingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crisisGroupBox.sizePolicy().hasHeightForWidth())
        self.crisisGroupBox.setSizePolicy(sizePolicy)
        self.crisisGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.crisisGroupBox.setObjectName("crisisGroupBox")
        self.crisisGroupBoxLayout = QtWidgets.QVBoxLayout(self.crisisGroupBox)
        self.crisisGroupBoxLayout.setSpacing(0)
        self.crisisGroupBoxLayout.setObjectName("crisisGroupBoxLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.crisisGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 231, 190))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.crisisFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crisisFrame.sizePolicy().hasHeightForWidth())
        self.crisisFrame.setSizePolicy(sizePolicy)
        self.crisisFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.crisisFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.crisisFrame.setObjectName("crisisFrame")
        self.hl3 = QtWidgets.QHBoxLayout(self.crisisFrame)
        self.hl3.setContentsMargins(-1, 2, -1, 2)
        self.hl3.setObjectName("hl3")
        self.crisisCB = QtWidgets.QCheckBox(self.crisisFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crisisCB.sizePolicy().hasHeightForWidth())
        self.crisisCB.setSizePolicy(sizePolicy)
        self.crisisCB.setChecked(False)
        self.crisisCB.setObjectName("crisisCB")
        self.hl3.addWidget(self.crisisCB)
        self.deleteCrisis = QtWidgets.QToolButton(self.crisisFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteCrisis.sizePolicy().hasHeightForWidth())
        self.deleteCrisis.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/times.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteCrisis.setIcon(icon2)
        self.deleteCrisis.setIconSize(QtCore.QSize(20, 20))
        self.deleteCrisis.setObjectName("deleteCrisis")
        self.hl3.addWidget(self.deleteCrisis)
        self.verticalLayout.addWidget(self.crisisFrame)
        self.crisisFrame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crisisFrame_2.sizePolicy().hasHeightForWidth())
        self.crisisFrame_2.setSizePolicy(sizePolicy)
        self.crisisFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.crisisFrame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.crisisFrame_2.setObjectName("crisisFrame_2")
        self.hl3_2 = QtWidgets.QHBoxLayout(self.crisisFrame_2)
        self.hl3_2.setContentsMargins(-1, 2, -1, 2)
        self.hl3_2.setObjectName("hl3_2")
        self.crisisCB_2 = QtWidgets.QCheckBox(self.crisisFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crisisCB_2.sizePolicy().hasHeightForWidth())
        self.crisisCB_2.setSizePolicy(sizePolicy)
        self.crisisCB_2.setChecked(False)
        self.crisisCB_2.setObjectName("crisisCB_2")
        self.hl3_2.addWidget(self.crisisCB_2)
        self.deleteCrisis_2 = QtWidgets.QToolButton(self.crisisFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteCrisis_2.sizePolicy().hasHeightForWidth())
        self.deleteCrisis_2.setSizePolicy(sizePolicy)
        self.deleteCrisis_2.setIcon(icon2)
        self.deleteCrisis_2.setIconSize(QtCore.QSize(20, 20))
        self.deleteCrisis_2.setObjectName("deleteCrisis_2")
        self.hl3_2.addWidget(self.deleteCrisis_2)
        self.verticalLayout.addWidget(self.crisisFrame_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.crisisGroupBoxLayout.addWidget(self.scrollArea)
        self.labelingLayout.addWidget(self.crisisGroupBox)
        self.customCrisisFrame = QtWidgets.QFrame(self.labelingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customCrisisFrame.sizePolicy().hasHeightForWidth())
        self.customCrisisFrame.setSizePolicy(sizePolicy)
        self.customCrisisFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.customCrisisFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.customCrisisFrame.setObjectName("customCrisisFrame")
        self._4 = QtWidgets.QHBoxLayout(self.customCrisisFrame)
        self._4.setContentsMargins(-1, -1, 19, -1)
        self._4.setObjectName("_4")
        self.customCrisisLine = QtWidgets.QLineEdit(self.customCrisisFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customCrisisLine.sizePolicy().hasHeightForWidth())
        self.customCrisisLine.setSizePolicy(sizePolicy)
        self.customCrisisLine.setObjectName("customCrisisLine")
        self._4.addWidget(self.customCrisisLine)
        self.addCustomButton = QtWidgets.QToolButton(self.customCrisisFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addCustomButton.setIcon(icon3)
        self.addCustomButton.setIconSize(QtCore.QSize(20, 20))
        self.addCustomButton.setObjectName("addCustomButton")
        self._4.addWidget(self.addCustomButton)
        self.labelingLayout.addWidget(self.customCrisisFrame)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.labelingLayout.addItem(spacerItem)
        self.fontFrame = QtWidgets.QFrame(self.labelingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontFrame.sizePolicy().hasHeightForWidth())
        self.fontFrame.setSizePolicy(sizePolicy)
        self.fontFrame.setObjectName("fontFrame")
        self.fontLayout = QtWidgets.QHBoxLayout(self.fontFrame)
        self.fontLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.fontLayout.setObjectName("fontLayout")
        self.fontComboBox = QtWidgets.QFontComboBox(self.fontFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBox.sizePolicy().hasHeightForWidth())
        self.fontComboBox.setSizePolicy(sizePolicy)
        self.fontComboBox.setMaximumSize(QtCore.QSize(278, 27))
        self.fontComboBox.setFontFilters(QtWidgets.QFontComboBox.ProportionalFonts)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.fontLayout.addWidget(self.fontComboBox)
        self.pointSizeSpinBox = QtWidgets.QSpinBox(self.fontFrame)
        self.pointSizeSpinBox.setMinimum(5)
        self.pointSizeSpinBox.setMaximum(30)
        self.pointSizeSpinBox.setProperty("value", 11)
        self.pointSizeSpinBox.setObjectName("pointSizeSpinBox")
        self.fontLayout.addWidget(self.pointSizeSpinBox)
        self.labelingLayout.addWidget(self.fontFrame)
        self.hl_5.addWidget(self.labelingFrame)

        self.retranslateUi(LabelingWidget)
        self.deleteCrisis.clicked.connect(self.crisisFrame.deleteLater)
        self.addCustomButton.clicked.connect(self.crisisGroupBox.setFocus)
        QtCore.QMetaObject.connectSlotsByName(LabelingWidget)
        LabelingWidget.setTabOrder(self.journalEntryText, self.deleteCrisis)
        LabelingWidget.setTabOrder(self.deleteCrisis, self.addCustomButton)
        LabelingWidget.setTabOrder(self.addCustomButton, self.backButton)
        LabelingWidget.setTabOrder(self.backButton, self.forwardButton)
        LabelingWidget.setTabOrder(self.forwardButton, self.fontComboBox)
        LabelingWidget.setTabOrder(self.fontComboBox, self.pointSizeSpinBox)

    def retranslateUi(self, LabelingWidget):
        _translate = QtCore.QCoreApplication.translate
        LabelingWidget.setWindowTitle(_translate("LabelingWidget", "ALJI Label Helper Task"))
        self.journalEntryText.setHtml(_translate("LabelingWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.journalEntryText.setPlaceholderText(_translate("LabelingWidget", "PLACEHOLDER TEXT"))
        self.backButton.setText(_translate("LabelingWidget", "Back"))
        self.backButton.setShortcut(_translate("LabelingWidget", "Ctrl+Left"))
        self.taskNumberLabel.setText(_translate("LabelingWidget", "Journal Entry ??/??"))
        self.forwardButton.setText(_translate("LabelingWidget", "Forward"))
        self.forwardButton.setShortcut(_translate("LabelingWidget", "Ctrl+Right"))
        self.cgiLabel.setToolTip(_translate("LabelingWidget", "Clinician Global Impression of Severity Scale"))
        self.cgiLabel.setWhatsThis(_translate("LabelingWidget", "CGI-S is the Clinician Global Impression of Severity Scale"))
        self.cgiLabel.setText(_translate("LabelingWidget", "CGI-S rating"))
        self.crisisGroupBox.setTitle(_translate("LabelingWidget", "Labels"))
        self.crisisCB.setText(_translate("LabelingWidget", "Crisis1"))
        self.deleteCrisis.setText(_translate("LabelingWidget", "Delete"))
        self.crisisCB_2.setText(_translate("LabelingWidget", "Crisis1"))
        self.deleteCrisis_2.setText(_translate("LabelingWidget", "Delete"))
        self.customCrisisLine.setPlaceholderText(_translate("LabelingWidget", "new custom label"))
        self.addCustomButton.setText(_translate("LabelingWidget", "Add"))
        self.pointSizeSpinBox.setSuffix(_translate("LabelingWidget", " pt."))

