# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/LabelingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LabelingWidget(object):
    def setupUi(self, LabelingWidget):
        LabelingWidget.setObjectName("LabelingWidget")
        LabelingWidget.setBaseSize(QtCore.QSize(1080, 960))
        font = QtGui.QFont()
        font.setPointSize(13)
        LabelingWidget.setFont(font)
        self.hl_5 = QtWidgets.QHBoxLayout(LabelingWidget)
        self.hl_5.setObjectName("hl_5")
        self.journalEntryText = QtWidgets.QTextEdit(LabelingWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journalEntryText.sizePolicy().hasHeightForWidth())
        self.journalEntryText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.journalEntryText.setFont(font)
        self.journalEntryText.setMouseTracking(True)
        self.journalEntryText.setReadOnly(True)
        self.journalEntryText.setObjectName("journalEntryText")
        self.hl_5.addWidget(self.journalEntryText)
        self.labelingFrame = QtWidgets.QFrame(LabelingWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelingFrame.sizePolicy().hasHeightForWidth())
        self.labelingFrame.setSizePolicy(sizePolicy)
        self.labelingFrame.setObjectName("labelingFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.labelingFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navFrame = QtWidgets.QFrame(self.labelingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navFrame.sizePolicy().hasHeightForWidth())
        self.navFrame.setSizePolicy(sizePolicy)
        self.navFrame.setObjectName("navFrame")
        self.navLayout = QtWidgets.QHBoxLayout(self.navFrame)
        self.navLayout.setSpacing(20)
        self.navLayout.setObjectName("navLayout")
        self.backButton = QtWidgets.QToolButton(self.navFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/chevron-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon)
        self.backButton.setIconSize(QtCore.QSize(20, 20))
        self.backButton.setObjectName("backButton")
        self.navLayout.addWidget(self.backButton)
        self.taskNumberLabel = QtWidgets.QLabel(self.navFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskNumberLabel.sizePolicy().hasHeightForWidth())
        self.taskNumberLabel.setSizePolicy(sizePolicy)
        self.taskNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.taskNumberLabel.setObjectName("taskNumberLabel")
        self.navLayout.addWidget(self.taskNumberLabel)
        self.forwardButton = QtWidgets.QToolButton(self.navFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forwardButton.sizePolicy().hasHeightForWidth())
        self.forwardButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/chevron-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon1)
        self.forwardButton.setIconSize(QtCore.QSize(20, 20))
        self.forwardButton.setObjectName("forwardButton")
        self.navLayout.addWidget(self.forwardButton)
        self.verticalLayout.addWidget(self.navFrame)
        self.cgiFrame = QtWidgets.QFrame(self.labelingFrame)
        self.cgiFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cgiFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cgiFrame.setObjectName("cgiFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.cgiFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cgiLabel = QtWidgets.QLabel(self.cgiFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cgiLabel.sizePolicy().hasHeightForWidth())
        self.cgiLabel.setSizePolicy(sizePolicy)
        self.cgiLabel.setObjectName("cgiLabel")
        self.horizontalLayout.addWidget(self.cgiLabel)
        self.cgiSpinBox = QtWidgets.QSpinBox(self.cgiFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cgiSpinBox.sizePolicy().hasHeightForWidth())
        self.cgiSpinBox.setSizePolicy(sizePolicy)
        self.cgiSpinBox.setMinimum(1)
        self.cgiSpinBox.setMaximum(7)
        self.cgiSpinBox.setObjectName("cgiSpinBox")
        self.horizontalLayout.addWidget(self.cgiSpinBox)
        self.verticalLayout.addWidget(self.cgiFrame)
        self.labelsLabel = QtWidgets.QLabel(self.labelingFrame)
        self.labelsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.labelsLabel.setObjectName("labelsLabel")
        self.verticalLayout.addWidget(self.labelsLabel)
        self.labelScrollArea = QtWidgets.QScrollArea(self.labelingFrame)
        self.labelScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.labelScrollArea.setWidgetResizable(True)
        self.labelScrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelScrollArea.setObjectName("labelScrollArea")
        self.labelScrollAreaWidgetContents = QtWidgets.QWidget()
        self.labelScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 528, 228))
        self.labelScrollAreaWidgetContents.setObjectName("labelScrollAreaWidgetContents")
        self.labelScrollAreaLayout = QtWidgets.QVBoxLayout(self.labelScrollAreaWidgetContents)
        self.labelScrollAreaLayout.setObjectName("labelScrollAreaLayout")
        self.crisisFrame = QtWidgets.QFrame(self.labelScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crisisFrame.sizePolicy().hasHeightForWidth())
        self.crisisFrame.setSizePolicy(sizePolicy)
        self.crisisFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.crisisFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.crisisFrame.setObjectName("crisisFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.crisisFrame)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.crisisCB = QtWidgets.QCheckBox(self.crisisFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crisisCB.sizePolicy().hasHeightForWidth())
        self.crisisCB.setSizePolicy(sizePolicy)
        self.crisisCB.setChecked(False)
        self.crisisCB.setObjectName("crisisCB")
        self.horizontalLayout_2.addWidget(self.crisisCB)
        self.deleteCrisis = QtWidgets.QToolButton(self.crisisFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteCrisis.sizePolicy().hasHeightForWidth())
        self.deleteCrisis.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/times.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteCrisis.setIcon(icon2)
        self.deleteCrisis.setIconSize(QtCore.QSize(20, 20))
        self.deleteCrisis.setObjectName("deleteCrisis")
        self.horizontalLayout_2.addWidget(self.deleteCrisis)
        self.labelScrollAreaLayout.addWidget(self.crisisFrame)
        self.crisisFrame_6 = QtWidgets.QFrame(self.labelScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crisisFrame_6.sizePolicy().hasHeightForWidth())
        self.crisisFrame_6.setSizePolicy(sizePolicy)
        self.crisisFrame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.crisisFrame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.crisisFrame_6.setObjectName("crisisFrame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.crisisFrame_6)
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.crisisCB_6 = QtWidgets.QCheckBox(self.crisisFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crisisCB_6.sizePolicy().hasHeightForWidth())
        self.crisisCB_6.setSizePolicy(sizePolicy)
        self.crisisCB_6.setChecked(False)
        self.crisisCB_6.setObjectName("crisisCB_6")
        self.horizontalLayout_7.addWidget(self.crisisCB_6)
        self.deleteCrisis_6 = QtWidgets.QToolButton(self.crisisFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteCrisis_6.sizePolicy().hasHeightForWidth())
        self.deleteCrisis_6.setSizePolicy(sizePolicy)
        self.deleteCrisis_6.setIcon(icon2)
        self.deleteCrisis_6.setIconSize(QtCore.QSize(20, 20))
        self.deleteCrisis_6.setObjectName("deleteCrisis_6")
        self.horizontalLayout_7.addWidget(self.deleteCrisis_6)
        self.labelScrollAreaLayout.addWidget(self.crisisFrame_6)
        self.labelScrollArea.setWidget(self.labelScrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.labelScrollArea)
        self.customCrisisFrame = QtWidgets.QFrame(self.labelingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customCrisisFrame.sizePolicy().hasHeightForWidth())
        self.customCrisisFrame.setSizePolicy(sizePolicy)
        self.customCrisisFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.customCrisisFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.customCrisisFrame.setObjectName("customCrisisFrame")
        self._4 = QtWidgets.QHBoxLayout(self.customCrisisFrame)
        self._4.setObjectName("_4")
        self.customCrisisLine = QtWidgets.QLineEdit(self.customCrisisFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customCrisisLine.sizePolicy().hasHeightForWidth())
        self.customCrisisLine.setSizePolicy(sizePolicy)
        self.customCrisisLine.setObjectName("customCrisisLine")
        self._4.addWidget(self.customCrisisLine)
        self.addCustomButton = QtWidgets.QToolButton(self.customCrisisFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addCustomButton.setIcon(icon3)
        self.addCustomButton.setIconSize(QtCore.QSize(20, 20))
        self.addCustomButton.setObjectName("addCustomButton")
        self._4.addWidget(self.addCustomButton)
        self.verticalLayout.addWidget(self.customCrisisFrame)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.fontFrame = QtWidgets.QFrame(self.labelingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontFrame.sizePolicy().hasHeightForWidth())
        self.fontFrame.setSizePolicy(sizePolicy)
        self.fontFrame.setObjectName("fontFrame")
        self.fontLayout = QtWidgets.QHBoxLayout(self.fontFrame)
        self.fontLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.fontLayout.setObjectName("fontLayout")
        self.fontComboBox = QtWidgets.QFontComboBox(self.fontFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBox.sizePolicy().hasHeightForWidth())
        self.fontComboBox.setSizePolicy(sizePolicy)
        self.fontComboBox.setMaximumSize(QtCore.QSize(278, 27))
        self.fontComboBox.setFontFilters(QtWidgets.QFontComboBox.ProportionalFonts)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.fontLayout.addWidget(self.fontComboBox)
        self.pointSizeSpinBox = QtWidgets.QSpinBox(self.fontFrame)
        self.pointSizeSpinBox.setMinimum(5)
        self.pointSizeSpinBox.setMaximum(30)
        self.pointSizeSpinBox.setProperty("value", 11)
        self.pointSizeSpinBox.setObjectName("pointSizeSpinBox")
        self.fontLayout.addWidget(self.pointSizeSpinBox)
        self.verticalLayout.addWidget(self.fontFrame)
        self.hl_5.addWidget(self.labelingFrame, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(LabelingWidget)
        self.deleteCrisis.clicked.connect(self.crisisFrame.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(LabelingWidget)
        LabelingWidget.setTabOrder(self.journalEntryText, self.deleteCrisis)
        LabelingWidget.setTabOrder(self.deleteCrisis, self.addCustomButton)
        LabelingWidget.setTabOrder(self.addCustomButton, self.backButton)
        LabelingWidget.setTabOrder(self.backButton, self.forwardButton)
        LabelingWidget.setTabOrder(self.forwardButton, self.fontComboBox)
        LabelingWidget.setTabOrder(self.fontComboBox, self.pointSizeSpinBox)

    def retranslateUi(self, LabelingWidget):
        _translate = QtCore.QCoreApplication.translate
        LabelingWidget.setWindowTitle(_translate("LabelingWidget", "ALJI Label Helper Task"))
        self.journalEntryText.setHtml(_translate("LabelingWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.journalEntryText.setPlaceholderText(_translate("LabelingWidget", "PLACEHOLDER TEXT"))
        self.backButton.setText(_translate("LabelingWidget", "Back"))
        self.backButton.setShortcut(_translate("LabelingWidget", "Ctrl+Left"))
        self.taskNumberLabel.setText(_translate("LabelingWidget", "Journal Entry ??/??"))
        self.forwardButton.setText(_translate("LabelingWidget", "Forward"))
        self.forwardButton.setShortcut(_translate("LabelingWidget", "Ctrl+Right"))
        self.cgiLabel.setToolTip(_translate("LabelingWidget", "Clinician Global Impression of Severity Scale"))
        self.cgiLabel.setWhatsThis(_translate("LabelingWidget", "CGI-S is the Clinician Global Impression of Severity Scale"))
        self.cgiLabel.setText(_translate("LabelingWidget", "CGI-S rating"))
        self.labelsLabel.setText(_translate("LabelingWidget", "Labels"))
        self.crisisCB.setText(_translate("LabelingWidget", "Crisis1"))
        self.deleteCrisis.setText(_translate("LabelingWidget", "Delete"))
        self.crisisCB_6.setText(_translate("LabelingWidget", "Crisis Crisis Crisis Crisis Crisis "))
        self.deleteCrisis_6.setText(_translate("LabelingWidget", "Delete"))
        self.customCrisisLine.setPlaceholderText(_translate("LabelingWidget", "new custom label"))
        self.addCustomButton.setText(_translate("LabelingWidget", "Add"))
        self.pointSizeSpinBox.setSuffix(_translate("LabelingWidget", " pt."))

from .images import icons_rc
