github:
  url: https://github.com/sublime09/ALJI
encoding: UTF-8
kramdown:
  input: GFM
  # hard_wrap: false
future: true
jailed: false
# theme: jekyll-theme-primer
# theme: jekyll-theme-modernist
theme: jekyll-theme-slate
gfm_quirks: paragraph_end

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true